#pragma once
#include <pcap.h>
#include <QtWidgets>
#include <QtConcurrent/QtConcurrent>
#include <string>
#include <vector>
#include <array>
#include <map>
#include <optional>
#include <functional>
#include <filesystem>
